# Generated by Django 4.2.6 on 2023-10-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='titulo',
        ),
    ]
