# Generated by Django 4.2.6 on 2024-05-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pregunta_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
